// <auto-generated />
namespace Rent_a_car.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Arnela : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Arnela));
        
        string IMigrationMetadata.Id
        {
            get { return "201612192011106_Arnela"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
