// <auto-generated />
namespace Rent_a_car.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class newmigs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newmigs));
        
        string IMigrationMetadata.Id
        {
            get { return "201702242035217_newmigs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
